### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by mrcbq** [mrcbq/catalog-of-my-things#47]
Hello, We are 3 in this group my partners

@romans-adi Team Member #1
@mrcbq Team Member #2
@lincoln1883 Team Member #3

- [x] This is the link to the Kanban [https://github.com/mrcbq/catalog-of-my-things/projects/2](https://github.com/mrcbq/catalog-of-my-things/projects/2)

**Comment by Owusu-Desmond** [comment]
Hi @mrcbq, @romans-adi , and @lincoln1883 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
📌 Descriptive issue✅
📌 Great working on the set up of the project board✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
